### ISSUE TITLE
🐛 for not displayed in HTML

### ISSUE THREAD

**Issue by bwnstck** [divSchubser/TheWeatherCompany#12]
https://github.com/divSchubser/TheWeatherCompany/blob/02c710da37cc09fb31438eba32b6f630842c2f64/src/components/Form.js#L6

<img width="437" alt="LabelBug" src="https://user-images.githubusercontent.com/37471898/97077813-104c5a00-15e7-11eb-9ec3-ddac5307d72c.png">

`<label for="...">` ist not displayed… but why? 👾

**Comment by AlexisRoe** [comment]
do you tried to implement it with two buttons and depending on which button the user clicks, show them different pictures

**Comment by AlexisRoe** [comment]
why assigning for two times? you can also place the input inside the label to connect them

**Comment by AlexisRoe** [comment]
is there enough space to show the label?

**Comment by bwnstck** [comment]
> why assigning for two times? you can also place the input inside the label to connect them

to see if the `createElement()`function fails… but even the second try fails 😶

**Comment by bwnstck** [comment]
okey … solved it with `  kittyLabel.setAttribute("for", "kittyCheck"); `

but if someone could explain why the other methods doesnt work, would be nice :)

**Comment by lmachens** [comment]
It's `htmlFor` in Javascript.
`for` is a reserved word, similar to `class`.

**Comment by bwnstck** [comment]
yes I already thought so… but is this the only way to solve it? Because  i couldnt find an alternative like for class and className. But thanks for the hint anyway 🚀
